---
- hosts: server
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - hostname
    - common
    - docker-common
    - influxdb-docker
    - elk-docker
    - grafana-docker
    - riemann-docker
