---
- name: Ensure ZooKeeper docker configuration directory exists
  file: path={{zookeeper_docker_conf_dir.host_path}} state=directory

- name: Ensure ZooKeeper data directory exists
  file: path={{ zookeeper_host_data_dir }} state=directory
  when: zookeeper_data_directories_configuration == "provided"

- name: Ensure ZooKeeper data log directory exists
  file: path={{ zookeeper_host_data_log_dir }} state=directory
  when: zookeeper_data_directories_configuration == "provided"

- name: Create ZooKeeper configuration from template
  template: src=zoo.cfg.j2 dest={{ zookeeper_docker_conf_dir.host_path }}/zoo.cfg

- name: Copy log4j property file
  copy:
    src: files/log4j.properties
    dest: "{{ zookeeper_docker_conf_dir.host_path }}/log4j.properties"

- include: start-zookeeper-data-container.yml
- include: start-zookeeper-container.yml
