---
- name: Create ZooKeeper data container
  docker_container:
    name: "zookeeper_data_{{ inventory_hostname_short }}"
    image: busybox
    state: present
    volumes:
      - "{{ zookeeper_data_dir }}"
  when: zookeeper_data_directories_configuration == "container"
