---
ec2_key_name: dummy-key
ec2_group: dummy-group
ec2_image_id: ami-26c43149
ec2_instance_type: t2.micro
ec2_region: eu-central-1
ec2_volumes: null
ec2_tags: {}
ec2_security_group: dummy-group
ec2_subnet_id: dummy-subnet
ec2_count: 1
ec2_profile_name: null
