# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian7"
  config.vm.box_url = "file:///Users/nenadbozic/Development/VM/debian-wheezy-64.box"

  # Turn off shared folders
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  # Database server
  config.vm.define "database" do |database|
    database.vm.hostname = "cassandra"
    database.vm.network "private_network", ip: "192.168.34.20"

    database.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--memory", "1024" ]
    end
  end
end
