VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Database server
  config.vm.define "database" do |database|
    database.vm.hostname = "cassandra"
    database.vm.network "private_network", ip: "192.168.34.20"

    database.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--memory", "2048" ]
    end
  end
end
