---
#################################
# Project
#################################

project_id: cassandra
java_version: java8jre

#################################
# Application layer
#################################


#################################
# Database layer
#################################

kernel_params:
  - { name: net.ipv4.tcp_rmem, value: "4096 87380 16777216" }
  - { name: net.ipv4.tcp_wmem, value: "4096 65536 16777216" }
  - { name: net.ipv4.tcp_ecn, value: 0 }
  - { name: net.ipv4.tcp_window_scaling, value: 1 }
  - { name: net.ipv4.ip_local_port_range, value: "10000 65535" }
  - { name: net.ipv4.tcp_tw_recycle, value: 1 }
  - { name: net.core.rmem_max, value: 16777216 }
  - { name: net.core.wmem_max, value: 16777216 }
  - { name: net.core.somaxconn, value: 4096 }
  - { name: net.core.netdev_max_backlog, value: 16384 }
  - { name: vm.swappiness, value: 1 }
  - { name: vm.max_map_count, value: 1073741824 }
  - { name: vm.dirty_background_bytes, value: 10485760 }
  - { name: vm.dirty_bytes, value: 1073741824 }
  - { name: fs.file-max, value: 1073741824 }
  - { name: vm.min_free_kbytes, value: 1048576 }

#################################
# Application configuration
#################################
