- name: Set hostname
  hostname: name={{ inventory_hostname }}

- name: Add hosts entry
  lineinfile: dest=/etc/hosts state=present mode=0644 regexp="{{ ansible_ssh_host }}.*"
    line="{{ ansible_ssh_host }} {{ inventory_hostname | regex_replace('^(.*)\..*$', '\\1') }} {{ inventory_hostname }}"
