---
  - name: Ensure Grafana config directory
    file: path={{ grafana_config_path }} owner=root group=root state=directory

  - name: Ensure Grafana data directory
    file: path={{ grafana_data_path }} owner=root group=root state=directory

  - name: Grafana config file
    template: src=grafana.ini.j2 dest={{ grafana_config_path }}/grafana.ini mode=0755
    register: grafana_config_ready

  - name: Ensure Grafana docker container
    docker:
      name: grafana
      image: "{{ grafana_docker_image }}"
      state: reloaded
      log_driver: "json-file"
      log_opt:
          "max-file": "2"
          "max-size": "10m"
      restart_policy: always
      ports:
        - "{{ grafana_console_port }}:3000"
      env:
        GF_SERVER_ROOT_URL: "{{ grafana_url }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_pwd }}"
      volumes:
        - "{{ grafana_config_path }}/grafana.ini:/etc/grafana/grafana.ini"
        - "{{ grafana_data_path }}:/var/lib/grafana"
    when: grafana_config_ready|success
    register: grafana_docker_container

  - name: Wait for Grafana API to start
    uri:
      url: "{{ grafana_url }}/api/dashboards/home"
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      return_content: yes
      status_code: 200
    until: grafana_api_ready|success
    retries: 10
    delay: 10
    when: grafana_docker_container|success
    register: grafana_api_ready

  - name: Fetching Grafana Influx DataSource
    uri:
      url: "{{ grafana_url }}/api/datasources/name/InfluxDB"
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      return_content: yes
      status_code: 200, 404
    register: influx_datasource_result
    when: grafana_api_ready|success

  - name: Creating Grafana default InfluxDB DataSource
    uri:
      url: "{{ grafana_url }}/api/datasources"
      method: POST
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      body_format: json
      body: "{{ lookup('template','influx_datasource.json.j2', convert_data=False) }}"
      status_code: 200
    when: influx_datasource_result.status == 404

  - name: Fetching Grafana ElasticSearch DataSource
    uri:
      url: "{{ grafana_url }}/api/datasources/name/ElasticSearch"
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      return_content: yes
      status_code: 200, 404
    register: elasticsearch_datasource_result
    when: grafana_api_ready|success

  - name: Creating Grafana default ElasticSearch DataSource
    uri:
      url: "{{ grafana_url }}/api/datasources"
      method: POST
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      body_format: json
      body: "{{ lookup('template','elasticsearch_datasource.json.j2', convert_data=False) }}"
      status_code: 200
    when: elasticsearch_datasource_result.status == 404

  - name: Searching for Grafana Overview Dashboards
    uri:
      url: "{{ grafana_url }}/api/dashboards/db/overview"
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      return_content: yes
      status_code: 200, 404
    register: grafana_overview_dashboard
    when: grafana_api_ready|success

  - name: Creating Grafana Overview Dashboard
    uri:
      url: "{{ grafana_url }}/api/dashboards/db"
      method: POST
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      body_format: json
      body: "{{ lookup('template','overview-dashboard.json.j2') | from_json }}"
      status_code: 200
    when: grafana_overview_dashboard.json.dashboard is not defined

  - name: Searching for Grafana Cluster Slow Queries Dashboards
    uri:
      url: "{{ grafana_url }}/api/dashboards/db/cluster-slow-queries"
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      return_content: yes
      status_code: 200, 404
    register: grafana_cluster_slow_queries_dashboard
    when: grafana_api_ready|success

  - name: Creating Grafana Cluster Slow Queries Dashboard
    uri:
      url: "{{ grafana_url }}/api/dashboards/db"
      method: POST
      force_basic_auth: yes
      user: "{{ grafana_admin_user }}"
      password: "{{ grafana_admin_pwd }}"
      body_format: json
      body: "{{ lookup('template','cluster-slow-queries-dashboard.json.j2') | from_json }}"
      status_code: 200
    when: grafana_cluster_slow_queries_dashboard.json.dashboard is not defined
