---
- name: Setup Cassandra cluster
  hosts: localhost
  connection: local
  roles:
    - role: aws
      ec2_key_name: "eu-smartcat"
      ec2_security_group: "sentinel"
      ec2_subnet_id: "subnet-f7825a9f"
      ec2_image_id: ami-26c43149
      ec2_instance_type: t2.medium
      ec2_region: eu-central-1
      ec2_count: 3
      ec2_tags:
        Name: "sentinel-cassandra"
      ec2_group: sentinel-cassandra
      ec2_profile_name: Kinesis-Producer

- name: Install software
  hosts: sentinel-cassandra
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tags:
    - aws-setup
    - aws-start
  pre_tasks:
    - name: Gathering facts
      setup:
      tags:
        - java
        - filebeat
        - telegraf-agent
        - cassandra
        - cassandra-diagnostics
  roles:
    - { role: java, tags: ["java"] }
    - { role: filebeat, tags: ["filebeat"] }
    - { role: telegraf-agent, tags: ["telegraf-agent"] }
    - { role: cassandra, tags: ["cassandra"] }
    - { role: cassandra-diagnostics, tags: ["cassandra-diagnostics"] }
