---
- name: Setup load generator
  hosts: localhost
  connection: local
  roles:
    - role: aws
      ec2_key_name: "eu-smartcat"
      ec2_security_group: "sentinel"
      ec2_subnet_id: "subnet-9c0af4e6"
      ec2_image_id: ami-26c43149
      ec2_instance_type: t2.large
      ec2_region: eu-central-1
      ec2_count: 1
      ec2_tags:
        Name: "sentinel-load"
      ec2_group: sentinel-load

- name: Install software
  hosts: sentinel-load
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tags:
    - aws-setup
    - aws-start
  pre_tasks:
    - name: Gathering facts
      setup:
      tags:
        - java
        - cassandra-tools
  roles:
    - { role: cassandra-tools, tags: ["cassandra-tools"] }
