---
- name: Setup Spark cluster
  hosts: localhost
  connection: local
  roles:
    - role: aws
      ec2_key_name: "eu-smartcat"
      ec2_security_group: "sentinel"
      ec2_subnet_id: "subnet-f7825a9f"
      ec2_image_id: ami-26c43149
      ec2_instance_type: t2.micro
      ec2_region: eu-central-1
      ec2_count: 4
      ec2_tags:
        Name: "sentinel-spark"
      ec2_group: sentinel-spark

- name: Install software
  hosts: sentinel-spark
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tags:
    - aws-setup
    - aws-start
  pre_tasks:
    - name: Gathering facts
      setup:
      tags:
        - spark
  roles:
    - { role: spark, tags: ["spark"] }
  post_tasks:
    - name: Start master
      shell: "{{ spark_home }}/sbin/start-master.sh"
      when: inventory_hostname == spark_master_ip
    - name: Start slaves
      shell: "{{ spark_home }}/sbin/start-slave.sh {{ spark_master_ip }}:{{ spark_master_port }}"
      when: inventory_hostname != spark_master_ip
