---
grafana_version: "3.1.1"
grafana_config_path: "/etc/grafana"
grafana_data_path: "/var/lib/grafana"
grafana_docker_image: "grafana/grafana:{{ grafana_version }}"
grafana_console_port: "3000"
grafana_url: "http://127.0.0.1:3000"
grafana_admin_user: "admin"
grafana_admin_pwd: "secret"

grafana_influxdb_url: "http://127.0.0.1:8086"
grafana_influxdb_db: "metric"
grafana_influxdb_user: "admin"
grafana_influxdb_pwd: "secret"
grafana_elasticsearch_url: "http://127.0.0.1:9020"
grafana_elasticsearch_db: "filebeat-*"
