- name: Install dependencies
  package: name=xfsprogs state=present

- name: Create data fs
  command: mkfs.xfs -s size=4096 /dev/xvdh

- name: Create mount folders
  file: path={{ item }} state=directory mode=0755
  with_items:
    - '{{ elk_elasticsearch_data_path }}'
    - '{{ influxdb_data_path }}'

- name: Update fstab
  lineinfile:
    dest: /etc/fstab
    line: '/dev/xvdh       {{ data_volume }}        xfs     defaults,noatime        0       0'

- name: Run mount all
  command: mount -a
