monitor_user: "admin"
monitor_pwd: "secret"
monitor_ip_addr: "192.168.35.30"
monitor_grafana_port: "3000"
monitor_influxdb_port: "8086"
monitor_influxdb_console_port: "8083"
monitor_influxdb_db: "metric"
monitor_riemann_port: "5555"

grafana_console_port: "{{ monitor_grafana_port }}"
grafana_url: "http://{{ monitor_ip_addr }}:{{ monitor_grafana_port }}"
grafana_admin_user: "{{ monitor_user }}"
grafana_admin_pwd: "{{ monitor_pwd }}"
grafana_influxdb_url: "http://{{ monitor_ip_addr }}:{{ monitor_influxdb_port }}"
grafana_influxdb_db: "{{ monitor_influxdb_db }}"
grafana_influxdb_user: "{{ monitor_user }}"
grafana_influxdb_pwd: "{{ monitor_pwd }}"

influxdb_version: "0.9"
influxdb_admin_user: "{{ monitor_user }}"
influxdb_admin_pwd: "{{ monitor_pwd }}"
influxdb_pre_created_db: "{{ monitor_influxdb_db }}"
influxdb_console_port: "{{ monitor_influxdb_console_port }}"
influxdb_api_port: "{{ monitor_influxdb_port }}"

riemann_influxdb_version: "{{ influxdb_version }} "
riemann_tcp_port: "{{ monitor_riemann_port }}"
riemann_udp_port: "{{ monitor_riemann_port }}"
riemann_influxdb_host: "{{ monitor_ip_addr }}"
riemann_influxdb_port: "{{ monitor_influxdb_port }}"
riemann_influxdb_db: "{{ monitor_influxdb_db }}"
riemann_influxdb_user: "{{ monitor_user }}"
riemann_influxdb_pwd: "{{ monitor_pwd }}"
