---
- name: Ensure Zabbix DB storage (MariaDB) volume
  docker:
    name: zabbix-db-storage
    image: busybox
    state: present
    log_driver: "json-file"
    log_opt:
        "max-file": "2"
        "max-size": "10m"
    volumes:
      - /var/lib/mysql

- name: Ensure Zabbix DB (MariaDB) is present
  docker:
    name: zabbix-db
    image: monitoringartist/zabbix-db-mariadb
    log_driver: "json-file"
    log_opt:
        "max-file": "2"
        "max-size": "10m"
    state: started
    ports:
      - "{{ zabbix_db_port }}:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    volumes_from:
      - zabbix-db-storage
    env:
      MARIADB_USER: "{{ zabbix_db_user }}"
      MARIADB_PASS: "{{ zabbix_db_password }}"

- name: Ensure Zabbix XXL server
  docker:
    name: zabbix
    image: "monitoringartist/zabbix-3.0-xxl:3.0.4"
    log_driver: "json-file"
    log_opt:
        "max-file": "2"
        "max-size": "10m"
    state: started
    ports:
      - "{{ zabbix_web_port }}:80"
      - "{{ zabbix_server_port }}:10051"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - "zabbix-db:zabbixdb"
    env:
      ZS_DBHost: zabbixdb
      ZS_DBUser: "{{ zabbix_db_user }}"
      ZS_DBPassword: "{{ zabbix_db_password }}"

