---
- name: Cassandra cluster
  hosts: localhost
  connection: local
  roles:
    - role: aws
      ec2_key_name: "eu-smartcat"
      ec2_security_group: "anomaly-stack"
      ec2_image_id: ami-26c43149
      ec2_instance_type: t2.micro
      ec2_region: eu-central-1
      ec2_count: 3
      ec2_tags:
        Name: "smart-cassandra"
      ec2_group: smart-cassandra

- name: Setup instances
  hosts: smart-cassandra
  gather_facts: False
  tags: ['aws-setup', 'aws-start']
  remote_user: ubuntu
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Gathering facts
      setup:
  roles:
    - java
    - filebeat
    - cassandra
    - cassandra-diagnostics
    - cassandra-metrics-reporter
    - osmetrics
