---
- name: smart-load-gen | Instance setup
  hosts: localhost
  connection: local
  roles:
    - role: aws
      ec2_key_name: "eu-smartcat"
      ec2_security_group: "anomaly-stack"
      ec2_image_id: ami-26c43149
      ec2_instance_type: t2.large
      ec2_region: eu-central-1
      ec2_count: 1
      ec2_tags:
        Name: "smart-load-gen"
      ec2_group: smart-load-gen

- name: smart-load-gen | Install software
  hosts: smart-load-gen
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tags:
    - aws-setup
    - aws-start
  pre_tasks:
    - name: Gathering facts
      setup:
  roles:
    - { role: java, tags: ["java"] }
    - { role: cassandra-tools, tags: ["cassandra-tools"] }
