---
- name: setup monitoring
  hosts: monitoring
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - docker-common
    - influxdb-docker
    - elk-docker
    - grafana-docker
    - riemann-docker
