---
- hosts: databaselayer
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - hostname
    - common
    - java
    - python
    - cassandra
    - cassandra-diagnostics
    - s3cmd
