---
cassandra_dsc_version: dsc21

cassandra_seed_0: '{{ hostvars[groups["smart-cassandra"][0]]["private_ip"] }}'
cassandra_seed_1: '{{ hostvars[groups["smart-cassandra"][1]]["private_ip"] }}'
cassandra_seed_2: '{{ hostvars[groups["smart-cassandra"][2]]["private_ip"] }}'
cassandra_seeds: "{{ cassandra_seed_0 }},{{ cassandra_seed_1 }},{{ cassandra_seed_2 }}"

cassandra_native_transport_port: 9042
cluster_name: App Cluster

cassandra_user: "root"
cassandra_configuration_dir: "/etc/cassandra/"
cassandra_env_max_heap_size: 512M
cassandra_env_heap_newsize: 100M

# Filebeat
filebeat_elasticsearch_hosts: "'{{ monitoring_node_private }}:9200'"

# Diagnostics
cassandra_diagnostics_version: "1.2.0"
cassandra_diagnostics_connector_version: "21"
cassandra_diagnostics_version_file: "/opt/cassandra-diagnostics.version"
cassandra_diagnostics_configuration_file: ../../anomaly-detection-stack/templates/cassandra-diagnostics.yml.j2
cassandra_diagnostics_target_dir: "/usr/share/cassandra/lib/"

cassandra_diagnostics_riemann_host: "{{ monitoring_node_private }}"
cassandra_diagnostics_riemann_port: 5555

riemann_server_address: "{{ monitoring_node_private }}"

cassandra_diagnostics_binaries:
  - "{{ cassandra_diagnostics_url_core }}"
  - "{{ cassandra_diagnostics_url_connector }}"
  - "{{ cassandra_diagnostics_url_reporter_riemann }}"

cassandra_diagnostics_jmx_host: 127.0.0.1
cassandra_diagnostics_jmx_port: 7199

# OS metrics
osmetrics_riemann_port: "{{ cassandra_diagnostics_riemann_port }}"
osmetrics_riemann_host: "{{ monitoring_node_private }}"
