---
  - name: Ensure InfluxDB data directory
    file: path={{ influxdb_data_path }} owner=root group=root state=directory

  - name: Ensure InfluxDB docker container
    docker: 
      name: influxdb
      image: "{{ influxdb_docker_image }}"
      state: reloaded
      log_driver: syslog
      restart_policy: always
      ports:
        - "{{ influxdb_console_port }}:8083"
        - "{{ influxdb_api_port }}:8086"  
      volumes:
        - "{{ influxdb_data_path }}:/data"
      env:
        ADMIN_USER: "{{ influxdb_admin_user }}"
        INFLUXDB_INIT_PWD: "{{ influxdb_admin_pwd }}"
        PRE_CREATE_DB: "{{ influxdb_pre_created_db }}"