VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  # GOCD server
  config.vm.define "ci-server" do |database|
    database.vm.network "private_network", ip: "192.168.33.20"

    database.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--memory", "2048" ]
    end
  end
end
